name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Simular deploy
        run: |
          echo "Iniciando deploy..."
          echo "Deploy da branch main realizado com sucesso"